import type { TripData } from "../types";

export const mockTripData: TripData = {
  id: "1",
  destination: "Tokyo, Japan",
  duration: "5 days, 4 nights",
  dates: "March 15-20, 2024",
  totalCost: 2850,
  createdAt: new Date("2024-01-01"),
  updatedAt: new Date("2024-01-01"),
  flightGroups: [
    {
      id: "1",
      tripId: "1",
      description: "Outbound flight to Japan with connection in Denver",
      totalPrice: 720,
      flights: [
        {
          id: "1",
          flightGroupId: "1",
          airline: "United Airlines",
          from: "LAX",
          fromCity: "Los Angeles",
          to: "DEN",
          toCity: "Denver",
          departureTime: "8:30 AM",
          arrivalTime: "11:45 AM",
          date: "Mar 15",
          arrivalDate: "Mar 16",
          duration: "2h 15m",
          aircraft: "Boeing 737-800",
          seat: "12A",
          price: 280,
        },
        {
          id: "2",
          flightGroupId: "1",
          airline: "Japan Airlines",
          from: "DEN",
          fromCity: "Denver",
          to: "NRT",
          toCity: "Tokyo Narita",
          departureTime: "1:30 PM",
          arrivalTime: "4:45 PM +1",
          date: "Mar 15",
          arrivalDate: "Mar 16",
          duration: "11h 15m",
          aircraft: "Boeing 787-9",
          seat: "15F",
          price: 440,
        },
      ],
      layoverTime: "1h 45m",
    },
    {
      id: "2",
      tripId: "1",
      description: "Return flight from Japan direct to Los Angeles",
      totalPrice: 640,
      flights: [
        {
          id: "3",
          flightGroupId: "2",
          airline: "Japan Airlines",
          from: "NRT",
          fromCity: "Tokyo Narita",
          to: "LAX",
          toCity: "Los Angeles",
          departureTime: "6:20 PM",
          arrivalTime: "11:30 AM",
          date: "Mar 20",
          arrivalDate: "Mar 21",
          duration: "9h 10m",
          aircraft: "Boeing 787-9",
          seat: "18C",
          price: 640,
        },
      ],
      layoverTime: "1h 45m",
    },
  ],
  hotels: [
    {
      id: "htl_1",
      tripId: "1",
      name: "Park Hyatt Tokyo",
      location: "Shinjuku",
      rating: 4.8,
      nights: 4,
      pricePerNight: 320,
      totalPrice: 1280,
      amenities: ["Free WiFi", "Spa", "Fitness Center", "Restaurant"],
    },
    {
      id: "htl_2",
      tripId: "1",
      name: "Hilton Tokyo",
      location: "Shinjuku",
      rating: 4.7,
      nights: 4,
      pricePerNight: 280,
      totalPrice: 1120,
      amenities: ["Free WiFi", "Spa", "Fitness Center", "Restaurant"],
    }
  ],
  restaurants: [
    {
      id: "rst_1",
      tripId: "1",
      name: "Sukiyabashi Jiro",
      type: "Sushi",
      rating: 4.9,
      priceRange: "$$$",
      location: "Ginza",
    },
    {
      id: "rst_2",
      tripId: "1",
      name: "Ramen Yashichi",
      type: "Ramen",
      rating: 4.7,
      priceRange: "$$",
      location: "Shibuya",
    },
    {
      id: "rst_3",
      tripId: "1",
      name: "Narisawa",
      type: "Fine Dining",
      rating: 4.8,
      priceRange: "$$$$",
      location: "Minato",
    },
  ],
  activities: [
    {
      id: "act_1",
      tripId: "1",
      name: "Senso-ji Temple",
      type: "Cultural",
      duration: "2 hours",
      price: 0,
      location: "Asakusa",
    },
    {
      id: "act_2",
      tripId: "1",
      name: "Tokyo Skytree",
      type: "Sightseeing",
      duration: "3 hours",
      price: 25,
      location: "Sumida",
    },
    {
      id: "act_3",
      tripId: "1",
      name: "Tsukiji Outer Market Food Tour",
      type: "Food & Culture",
      duration: "4 hours",
      price: 85,
      location: "Tsukiji",
    },
    {
      id: "act_4",
      tripId: "1",
      name: "Meiji Shrine",
      type: "Cultural",
      duration: "1.5 hours",
      price: 0,
      location: "Shibuya",
    },
  ],
  itinerary: [
    {
      id: "itn_1",
      tripId: "1",
      day: 1,
      title: "Arrival & Asakusa",
      activities: ["Arrive at NRT", "Check-in hotel", "Senso-ji Temple", "Dinner at Ramen Yashichi"],
    },
    {
      id: "itn_2",
      tripId: "1",
      day: 2,
      title: "Modern Tokyo",
      activities: ["Tokyo Skytree", "Lunch in Sumida", "Shibuya Crossing", "Meiji Shrine"],
    },
    {
      id: "itn_3",
      tripId: "1",
      day: 3,
      title: "Food & Culture",
      activities: ["Tsukiji Food Tour", "Imperial Palace Gardens", "Ginza shopping", "Sukiyabashi Jiro"],
    },
    {
      id: "itn_4",
      tripId: "1",
      day: 4,
      title: "Final Exploration",
      activities: ["Harajuku district", "Omotesando shopping", "Narisawa dinner", "Night views"],
    },
    {
      id: "itn_5",
      tripId: "1",
      day: 5,
      title: "Departure",
      activities: ["Hotel checkout", "Last-minute shopping", "Depart from NRT"],
    },
  ],
}